name: API Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  newman-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run API Tests
        run: |
          newman run postman_test.json \
          -e env.json \
          -r cli,htmlextra \
          --reporter-htmlextra-export reports/report.html

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: reports/report.html
